ALTER TYPE "MarketplaceChannel" ADD VALUE IF NOT EXISTS 'N11';
ALTER TYPE "MarketplaceChannel" ADD VALUE IF NOT EXISTS 'PAZARAMA';
ALTER TYPE "MarketplaceChannel" ADD VALUE IF NOT EXISTS 'PTTAVM';
ALTER TYPE "MarketplaceChannel" ADD VALUE IF NOT EXISTS 'CICEKSEPETI';
ALTER TYPE "MarketplaceChannel" ADD VALUE IF NOT EXISTS 'IDEFIX';
